package ans;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class D10_ReporterList {

	public static void main(String[] args) {

		String regex = "(.+)\r\n.+\r\n.+\r\n(.+)\r\n.+@(.+)\r\n.+\r\n";
		
		// 필요한 부분 ()로 그룹만들어서 사용함, 대충 한줄을 전부 만들어놓고 반복문

		Matcher matcher = Pattern.compile(regex).matcher(emails);

		Map<String, Integer> companyCount = new HashMap<>();
		Map<String, Integer> fieldCount = new HashMap<>();
		Map<String, Integer> domainCount = new HashMap<>();

		int i = 0;
		while (matcher.find()) {

			String company = matcher.group(1);
			String field = matcher.group(2);
			String domain = matcher.group(3);

			Integer cnt;
			
			if ((cnt = companyCount.putIfAbsent(company, 1)) != null) {
				companyCount.put(company, cnt + 1);
			}
			if ((cnt = fieldCount.putIfAbsent(field, 1)) != null) {
				fieldCount.put(field, cnt + 1);
			}
			if ((cnt = domainCount.putIfAbsent(domain, 1)) != null) {
				domainCount.put(domain, cnt + 1);
			}
			
//			System.out.printf("--%d --\n", i++);
//			System.out.println(matcher.group());
//			System.out.println("신문사: " + matcher.group(1));
//			System.out.println("분야: " + matcher.group(2));
//			System.out.println("도메인: " + matcher.group(3));
		}
		System.out.println(companyCount);
		System.out.println(fieldCount);
		System.out.println(domainCount);

	}

	final static String emails = "JTBC\r\n" + "이윤석\r\n" + "기자\r\n" + "경제\r\n" + "americano@jtbc.co.kr\r\n"
			+ "2016-10-18\r\n" + "JTBC\r\n" + "이창균\r\n" + "기자\r\n" + "경제\r\n" + "smilee@joongang.co.kr\r\n"
			+ "2017-03-29\r\n" + "JTBC\r\n" + "봉지욱\r\n" + "기자\r\n" + "사회\r\n" + "bong@jtbc.co.kr\r\n" + "2017-03-25\r\n"
			+ "JTBC\r\n" + "유주현\r\n" + "객원기자\r\n" + "생활/문화\r\n" + "yjjoo@joongang.co.kr\r\n" + "2017-03-26\r\n"
			+ "JTBC\r\n" + "박종근\r\n" + "기자\r\n" + "정치\r\n" + "nam.yoonseo1@joongang.co.kr\r\n" + "2017-03-31\r\n"
			+ "JTBC\r\n" + "이상언\r\n" + "기자\r\n" + "정치\r\n" + "joonny@joongang.co.kr\r\n" + "2016-12-22\r\n" + "JTBC\r\n"
			+ "이우연\r\n" + "인턴기자\r\n" + "정치\r\n" + "lee.jungmin@joongang.co.kr\r\n" + "2017-03-12\r\n" + "K STAR\r\n"
			+ "이보람\r\n" + "기자\r\n" + "생활/문화\r\n" + "brlee5655@gmail.com\r\n" + "2017-03-27\r\n" + "K STAR\r\n"
			+ "안지선\r\n" + "기자\r\n" + "생활/문화\r\n" + "ajs405@hanmail.net\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "범기영\r\n"
			+ "기자\r\n" + "IT\r\n" + "bum710@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "차정인\r\n" + "기자\r\n"
			+ "IT\r\n" + "jicha@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "임주현\r\n" + "기자\r\n" + "IT\r\n"
			+ "leg@kbs.co.kr\r\n" + "2017-03-12\r\n" + "KBS\r\n" + "최건일\r\n" + "기자\r\n" + "IT\r\n"
			+ "gaegoo@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "권명관\r\n" + "기자\r\n" + "IT\r\n"
			+ "dwarf@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "임종빈\r\n" + "기자\r\n" + "IT\r\n"
			+ "huimang@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "박예원\r\n" + "기자\r\n" + "IT\r\n"
			+ "air@kbs.co.kr\r\n" + "2016-12-13\r\n" + "KBS\r\n" + "송민석\r\n" + "기자\r\n" + "IT\r\n"
			+ "yesiwill@kbs.co.kr\r\n" + "2016-10-17\r\n" + "KBS\r\n" + "석혜원\r\n" + "기자\r\n" + "건강\r\n"
			+ "hey1@kbs.co.kr\r\n" + "2016-12-20\r\n" + "KBS\r\n" + "정지주\r\n" + "기자\r\n" + "건강\r\n"
			+ "jjcheong@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "박광식\r\n" + "기자\r\n" + "건강\r\n"
			+ "doctor@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "이재설\r\n" + "기자\r\n" + "건강\r\n"
			+ "record@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "윤봄이\r\n" + "기자\r\n" + "건강\r\n"
			+ "spring6727@gmail.com\r\n" + "2016-11-11\r\n" + "KBS\r\n" + "박석호\r\n" + "기자\r\n" + "경제\r\n"
			+ "parkseokho@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "변기성\r\n" + "기자\r\n" + "경제\r\n"
			+ "byun@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "구영희\r\n" + "기자\r\n" + "경제\r\n"
			+ "younghee@kbs.co.kr\r\n" + "2017-01-08\r\n" + "KBS\r\n" + "김영인\r\n" + "기자\r\n" + "경제\r\n"
			+ "heemang@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "박진영\r\n" + "기자\r\n" + "경제\r\n"
			+ "parkjy@kbs.co.kr\r\n" + "2017-03-09\r\n" + "KBS\r\n" + "지형철\r\n" + "기자\r\n" + "경제\r\n"
			+ "ican@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "정윤섭\r\n" + "기자\r\n" + "경제\r\n"
			+ "bird2777@kbs.co.kr\r\n" + "2017-03-06\r\n" + "KBS\r\n" + "김경진\r\n" + "기자\r\n" + "경제\r\n"
			+ "kjkim@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "송수진\r\n" + "기자\r\n" + "경제\r\n"
			+ "iam@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김현경\r\n" + "기자\r\n" + "경제\r\n"
			+ "hkkim@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "박종훈\r\n" + "기자\r\n" + "경제\r\n"
			+ "jonghoon@kbs.co.kr\r\n" + "2017-01-17\r\n" + "KBS\r\n" + "우한울\r\n" + "기자\r\n" + "경제\r\n"
			+ "whw@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김지선\r\n" + "기자\r\n" + "경제\r\n"
			+ "3rdline@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "최대수\r\n" + "기자\r\n" + "경제\r\n"
			+ "freehead@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "이재희\r\n" + "기자\r\n" + "경제\r\n"
			+ "leej@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "홍희정\r\n" + "기자\r\n" + "경제\r\n"
			+ "hjhong@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "임장원\r\n" + "기자\r\n" + "경제\r\n"
			+ "jwlim@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "최영철\r\n" + "기자\r\n" + "경제\r\n"
			+ "julio@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "송현정\r\n" + "기자\r\n" + "경제\r\n"
			+ "hjsong@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "김소영\r\n" + "기자\r\n" + "경제\r\n"
			+ "4right@kbs.co.kr\r\n" + "2017-02-23\r\n" + "KBS\r\n" + "박상용\r\n" + "기자\r\n" + "경제\r\n"
			+ "sangyong@kbs.co.kr\r\n" + "2017-03-22\r\n" + "KBS\r\n" + "한보경\r\n" + "기자\r\n" + "경제\r\n"
			+ "bkhan@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "김귀수\r\n" + "기자\r\n" + "경제\r\n"
			+ "seowoo10@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "임병걸\r\n" + "기자\r\n" + "경제\r\n"
			+ "kbslimbk@hanmail.net\r\n" + "2017-02-28\r\n" + "KBS\r\n" + "정윤섭\r\n" + "기자\r\n" + "경제\r\n"
			+ "winepark@kbs.co.kr\r\n" + "2016-12-14\r\n" + "KBS\r\n" + "김원장\r\n" + "기자\r\n" + "경제\r\n"
			+ "kim9@kbs.co.kr\r\n" + "2016-12-21\r\n" + "KBS\r\n" + "박현진\r\n" + "기자\r\n" + "경제\r\n"
			+ "laseule@kbs.co.kr\r\n" + "2016-12-13\r\n" + "KBS\r\n" + "민필규\r\n" + "기자\r\n" + "경제\r\n"
			+ "mrmin@kbs.co.kr\r\n" + "2016-12-10\r\n" + "KBS\r\n" + "홍사훈\r\n" + "기자\r\n" + "경제\r\n"
			+ "aristo@kbs.co.kr\r\n" + "2016-10-21\r\n" + "KBS\r\n" + "백운기\r\n" + "기자\r\n" + "경제\r\n"
			+ "ysooni@kbs.co.kr\r\n" + "2017-03-26\r\n" + "KBS\r\n" + "이영석\r\n" + "기자\r\n" + "경제\r\n"
			+ "zerostone@kbs.co.kr\r\n" + "2016-11-18\r\n" + "KBS\r\n" + "박유한\r\n" + "특파원\r\n" + "경제\r\n"
			+ "hanee@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "정다원\r\n" + "기자\r\n" + "과학\r\n"
			+ "mom@kbs.co.kr\r\n" + "2016-12-19\r\n" + "KBS\r\n" + "하초희\r\n" + "기자\r\n" + "도로/교통\r\n"
			+ "chohee25@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "김범수\r\n" + "기자\r\n" + "부동산\r\n"
			+ "kbs@chosunbiz.com\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "이연경\r\n" + "기자\r\n" + "사회\r\n"
			+ "yglee@kbs.co.kr\r\n" + "2017-03-06\r\n" + "KBS\r\n" + "송락규\r\n" + "기자\r\n" + "사회\r\n"
			+ "rockyou@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "박민철\r\n" + "기자\r\n" + "사회\r\n"
			+ "mcpark@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "안다영\r\n" + "기자\r\n" + "사회\r\n"
			+ "mauverine@kbs.co.kr\r\n" + "2017-03-05\r\n" + "KBS\r\n" + "신선민\r\n" + "기자\r\n" + "사회\r\n"
			+ "freshmin@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "송금한\r\n" + "기자\r\n" + "사회\r\n"
			+ "email@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "우정화\r\n" + "기자\r\n" + "사회\r\n"
			+ "jhw01@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "이정훈\r\n" + "기자\r\n" + "사회\r\n"
			+ "skyclear@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "윤창희\r\n" + "기자\r\n" + "사회\r\n"
			+ "theplay@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "천효정\r\n" + "기자\r\n" + "사회\r\n"
			+ "cheon@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "엄진아\r\n" + "기자\r\n" + "사회\r\n"
			+ "aza@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "이종완\r\n" + "기자\r\n" + "사회\r\n"
			+ "rjw2810@daum.net\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "이철호\r\n" + "기자\r\n" + "사회\r\n"
			+ "manjeok@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김민철\r\n" + "기자\r\n" + "사회\r\n"
			+ "mckim@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "이세중\r\n" + "기자\r\n" + "사회\r\n"
			+ "center@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김기화\r\n" + "기자\r\n" + "사회\r\n"
			+ "kimkoon@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "최혜진\r\n" + "기자\r\n" + "사회\r\n"
			+ "join@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "박혜진\r\n" + "기자\r\n" + "사회\r\n"
			+ "root@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "손서영\r\n" + "기자\r\n" + "사회\r\n"
			+ "bellesy@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "변진석\r\n" + "기자\r\n" + "사회\r\n"
			+ "jinsang81@kbs.co.kr\r\n" + "2016-06-07\r\n" + "KBS\r\n" + "노준철\r\n" + "기자\r\n" + "사회\r\n"
			+ "argos@kbs.co.kr\r\n" + "2017-03-15\r\n" + "KBS\r\n" + "송형국\r\n" + "기자\r\n" + "사회\r\n"
			+ "spianato@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "홍석우\r\n" + "기자\r\n" + "사회\r\n"
			+ "musehong@kbs.co.kr\r\n" + "2017-03-20\r\n" + "KBS\r\n" + "박병준\r\n" + "기자\r\n" + "사회\r\n"
			+ "lol@kbs.co.kr\r\n" + "2017-03-09\r\n" + "KBS\r\n" + "홍진아\r\n" + "기자\r\n" + "사회\r\n"
			+ "gina@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "임명규\r\n" + "기자\r\n" + "사회\r\n"
			+ "thelord@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "이현준\r\n" + "기자\r\n" + "사회\r\n"
			+ "hjni14@kbs.co.kr\r\n" + "2017-03-11\r\n" + "KBS\r\n" + "남범수\r\n" + "기자\r\n" + "사회\r\n"
			+ "alleylee@kbs.co.kr\r\n" + "2017-02-25\r\n" + "KBS\r\n" + "최준혁\r\n" + "기자\r\n" + "사회\r\n"
			+ "chunn@kbs.co.kr\r\n" + "2017-03-01\r\n" + "KBS\r\n" + "임서영\r\n" + "기자\r\n" + "사회\r\n"
			+ "mercy0@kbs.co.kr\r\n" + "2016-05-29\r\n" + "KBS\r\n" + "장성길\r\n" + "기자\r\n" + "사회\r\n"
			+ "skjang@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "한주연\r\n" + "기자\r\n" + "사회\r\n"
			+ "jyhan31@kbs.co.kr\r\n" + "2017-03-22\r\n" + "KBS\r\n" + "강성원\r\n" + "기자\r\n" + "사회\r\n"
			+ "kangsw@kbs.co.kr\r\n" + "2017-02-20\r\n" + "KBS\r\n" + "은준수\r\n" + "기자\r\n" + "사회\r\n"
			+ "eunjs@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "김유대\r\n" + "기자\r\n" + "사회\r\n"
			+ "ydkim@kbs.co.kr\r\n" + "2017-02-28\r\n" + "KBS\r\n" + "이승종\r\n" + "기자\r\n" + "사회\r\n"
			+ "argo@kbs.co.kr\r\n" + "2017-02-28\r\n" + "KBS\r\n" + "이세연\r\n" + "기자\r\n" + "사회\r\n"
			+ "say@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "이예진\r\n" + "기자\r\n" + "사회\r\n"
			+ "yejin.lee@kbs.co.kr\r\n" + "2017-02-19\r\n" + "KBS\r\n" + "김수연\r\n" + "기자\r\n" + "사회\r\n"
			+ "kbsksy@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "황현규\r\n" + "기자\r\n" + "사회\r\n"
			+ "true@kbs.co.kr\r\n" + "2017-03-16\r\n" + "KBS\r\n" + "노윤정\r\n" + "기자\r\n" + "사회\r\n"
			+ "watchdog@kbs.co.kr\r\n" + "2016-12-23\r\n" + "KBS\r\n" + "박지성\r\n" + "기자\r\n" + "사회\r\n"
			+ "jsp@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "오대성\r\n" + "기자\r\n" + "사회\r\n"
			+ "ohwhy@kbs.co.kr\r\n" + "2017-03-24\r\n" + "KBS\r\n" + "이대완\r\n" + "기자\r\n" + "사회\r\n"
			+ "bigbowl@kbs.co.kr\r\n" + "2017-03-01\r\n" + "KBS\r\n" + "오아영\r\n" + "기자\r\n" + "사회\r\n"
			+ "ayoung@kbs.co.kr\r\n" + "2017-03-04\r\n" + "KBS\r\n" + "임재성\r\n" + "기자\r\n" + "사회\r\n"
			+ "newsism@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "유지향\r\n" + "기자\r\n" + "사회\r\n"
			+ "nausika@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김성한\r\n" + "기자\r\n" + "사회\r\n"
			+ "albatross@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "김용덕\r\n" + "기자\r\n" + "사회\r\n"
			+ "kospirit@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "백미선\r\n" + "기자\r\n" + "사회\r\n"
			+ "bee@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "서재희\r\n" + "기자\r\n" + "사회\r\n"
			+ "seojh@kbs.co.kr\r\n" + "2016-11-28\r\n" + "KBS\r\n" + "김준원\r\n" + "기자\r\n" + "사회\r\n"
			+ "mondo@kbs.co.kr\r\n" + "2017-01-07\r\n" + "KBS\r\n" + "배태휴\r\n" + "기자\r\n" + "사회\r\n"
			+ "bthi12@kbs.co.kr\r\n" + "2017-01-15\r\n" + "KBS\r\n" + "지종익\r\n" + "기자\r\n" + "사회\r\n"
			+ "zgija@kbs.co.kr\r\n" + "2017-03-17\r\n" + "KBS\r\n" + "김보람\r\n" + "기자\r\n" + "사회\r\n"
			+ "bogu0602@kbs.co.kr\r\n" + "2017-03-05\r\n" + "KBS\r\n" + "주아랑\r\n" + "기자\r\n" + "사회\r\n"
			+ "hslp0110@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "신방실\r\n" + "기자\r\n" + "사회\r\n"
			+ "weezer@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김익태\r\n" + "기자\r\n" + "사회\r\n"
			+ "kit@kbs.co.kr\r\n" + "2016-12-09\r\n" + "KBS\r\n" + "최진아\r\n" + "기자\r\n" + "사회\r\n"
			+ "jina94@kbs.co.kr\r\n" + "2017-03-26\r\n" + "KBS\r\n" + "홍찬의\r\n" + "기자\r\n" + "사회\r\n"
			+ "cyhong@kbs.co.kr\r\n" + "2016-07-07\r\n" + "KBS\r\n" + "전영창\r\n" + "기자\r\n" + "사회\r\n"
			+ "dojeon@kbs.co.kr\r\n" + "2016-07-09\r\n" + "KBS\r\n" + "류란\r\n" + "기자\r\n" + "사회\r\n"
			+ "nany@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "옥유정\r\n" + "기자\r\n" + "사회\r\n"
			+ "okay@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "정연욱\r\n" + "기자\r\n" + "사회\r\n"
			+ "donkey@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "윤나경\r\n" + "기자\r\n" + "사회\r\n"
			+ "bellenk@kbs.co.kr\r\n" + "2017-02-19\r\n" + "KBS\r\n" + "이지현\r\n" + "기자\r\n" + "사회\r\n"
			+ "idl@kbs.co.kr\r\n" + "2016-10-08\r\n" + "KBS\r\n" + "오현태\r\n" + "기자\r\n" + "사회\r\n"
			+ "highfive@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "박재용\r\n" + "기자\r\n" + "사회\r\n"
			+ "pjyrep@kbs.co.kr\r\n" + "2017-03-01\r\n" + "KBS\r\n" + "이지윤\r\n" + "기자\r\n" + "사회\r\n"
			+ "easynews@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "안양봉\r\n" + "기자\r\n" + "사회\r\n"
			+ "beebee@kbs.co.kr\r\n" + "2016-08-20\r\n" + "KBS\r\n" + "정면구\r\n" + "기자\r\n" + "사회\r\n"
			+ "nine@kbs.co.kr\r\n" + "2017-03-11\r\n" + "KBS\r\n" + "조미령\r\n" + "기자\r\n" + "사회\r\n"
			+ "pearl@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "김진문\r\n" + "기자\r\n" + "사회\r\n"
			+ "jmkim@kbs.co.kr\r\n" + "2016-10-08\r\n" + "KBS\r\n" + "이재교\r\n" + "기자\r\n" + "사회\r\n"
			+ "sky77@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "최송현\r\n" + "기자\r\n" + "사회\r\n"
			+ "ssong@kbs.co.kr\r\n" + "2017-03-24\r\n" + "KBS\r\n" + "류재현\r\n" + "기자\r\n" + "사회\r\n"
			+ "jae@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "진유민\r\n" + "기자\r\n" + "사회\r\n"
			+ "realjin@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "김도훈\r\n" + "기자\r\n" + "사회\r\n"
			+ "kinchy@kbs.co.kr\r\n" + "2017-03-03\r\n" + "KBS\r\n" + "정제혁\r\n" + "기자\r\n" + "사회\r\n"
			+ "thomas@kbs.co.kr\r\n" + "2016-10-04\r\n" + "KBS\r\n" + "박중관\r\n" + "기자\r\n" + "사회\r\n"
			+ "jkp@kbs.co.kr\r\n" + "2017-03-04\r\n" + "KBS\r\n" + "염기석\r\n" + "기자\r\n" + "사회\r\n"
			+ "yks31@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "변진석\r\n" + "기자\r\n" + "사회\r\n"
			+ "lamer@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "이충헌\r\n" + "기자\r\n" + "사회\r\n"
			+ "chleemd@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "황경주\r\n" + "기자\r\n" + "사회\r\n"
			+ "race@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "김민지\r\n" + "기자\r\n" + "사회\r\n"
			+ "ming@kbs.co.kr\r\n" + "2017-02-18\r\n" + "KBS\r\n" + "이규명\r\n" + "기자\r\n" + "사회\r\n"
			+ "investigate@kbs.co.kr\r\n" + "2017-03-16\r\n" + "KBS\r\n" + "이하늬\r\n" + "기자\r\n" + "사회\r\n"
			+ "hanuy@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "황정호\r\n" + "기자\r\n" + "사회\r\n"
			+ "yellowcard@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "이종영\r\n" + "기자\r\n" + "사회\r\n"
			+ "myshk@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "이하경\r\n" + "기자\r\n" + "사회\r\n"
			+ "truth2004@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김영준\r\n" + "기자\r\n" + "사회\r\n"
			+ "yjkim1@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "유용두\r\n" + "기자\r\n" + "사회\r\n"
			+ "yyd9212@kbs.co.kr\r\n" + "2017-02-20\r\n" + "KBS\r\n" + "최재훈\r\n" + "기자\r\n" + "사회\r\n"
			+ "jhhs@kbs.co.kr\r\n" + "2016-10-29\r\n" + "KBS\r\n" + "이용순\r\n" + "기자\r\n" + "사회\r\n"
			+ "sh6558@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "이한글\r\n" + "기자\r\n" + "사회\r\n"
			+ "hanguri@kbs.co.kr\r\n" + "2016-10-05\r\n" + "KBS\r\n" + "이정은\r\n" + "기자\r\n" + "사회\r\n"
			+ "mulan8@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "하선아\r\n" + "기자\r\n" + "사회\r\n"
			+ "saha@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "국현호\r\n" + "기자\r\n" + "사회\r\n"
			+ "eichitwo@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김계애\r\n" + "기자\r\n" + "사회\r\n"
			+ "stone917@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "조정인\r\n" + "기자\r\n" + "사회\r\n"
			+ "j4u@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "최영윤\r\n" + "기자\r\n" + "사회\r\n"
			+ "freeyaw@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "이철재\r\n" + "기자\r\n" + "사회\r\n"
			+ "yeecj@kbs.co.kr\r\n" + "2016-10-08\r\n" + "KBS\r\n" + "양창희\r\n" + "기자\r\n" + "사회\r\n"
			+ "share@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김가람\r\n" + "기자\r\n" + "사회\r\n"
			+ "garam@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "강나래\r\n" + "기자\r\n" + "사회\r\n"
			+ "narae@kbs.co.kr\r\n" + "2017-03-24\r\n" + "KBS\r\n" + "김해정\r\n" + "기자\r\n" + "사회\r\n"
			+ "beinghj@kbs.co.kr\r\n" + "2017-02-16\r\n" + "KBS\r\n" + "엄경철\r\n" + "기자\r\n" + "사회\r\n"
			+ "eom@kbs.co.kr\r\n" + "2016-12-14\r\n" + "KBS\r\n" + "성용희\r\n" + "기자\r\n" + "사회\r\n"
			+ "heestory@kbs.co.kr\r\n" + "2017-03-24\r\n" + "KBS\r\n" + "공웅조\r\n" + "기자\r\n" + "사회\r\n"
			+ "salt@kbs.co.kr\r\n" + "2017-03-14\r\n" + "KBS\r\n" + "박영민\r\n" + "기자\r\n" + "사회\r\n"
			+ "youngmin@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "양희진\r\n" + "기자\r\n" + "사회\r\n"
			+ "julius@kbs.co.kr\r\n" + "2016-10-06\r\n" + "KBS\r\n" + "황정환\r\n" + "기자\r\n" + "사회\r\n"
			+ "baram@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "김영재\r\n" + "기자\r\n" + "사회\r\n"
			+ "cham@kbs.co.kr\r\n" + "2016-10-06\r\n" + "KBS\r\n" + "지용수\r\n" + "기자\r\n" + "사회\r\n"
			+ "water@kbs.co.kr\r\n" + "2017-03-07\r\n" + "KBS\r\n" + "김영중\r\n" + "기자\r\n" + "사회\r\n"
			+ "gnome@kbs.co.kr\r\n" + "2017-01-02\r\n" + "KBS\r\n" + "손원혁\r\n" + "기자\r\n" + "사회\r\n"
			+ "wh_son@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "홍정표\r\n" + "기자\r\n" + "사회\r\n"
			+ "real-eyes@kbs.co.kr\r\n" + "2017-01-05\r\n" + "KBS\r\n" + "정혜미\r\n" + "기자\r\n" + "사회\r\n"
			+ "with@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "안태성\r\n" + "기자\r\n" + "사회\r\n"
			+ "tsahn@kbs.co.kr\r\n" + "2016-12-10\r\n" + "KBS\r\n" + "김진화\r\n" + "기자\r\n" + "사회\r\n"
			+ "evolution@kbs.co.kr\r\n" + "2017-03-16\r\n" + "KBS\r\n" + "조경모\r\n" + "기자\r\n" + "사회\r\n"
			+ "jkm@kbs.co.kr\r\n" + "2017-03-17\r\n" + "KBS\r\n" + "곽근아\r\n" + "기자\r\n" + "사회\r\n"
			+ "charter77@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "허성권\r\n" + "기자\r\n" + "사회\r\n"
			+ "hsknews@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "진희정\r\n" + "기자\r\n" + "사회\r\n"
			+ "5w1h@kbs.co.kr\r\n" + "2017-03-16\r\n" + "KBS\r\n" + "박웅\r\n" + "기자\r\n" + "사회\r\n" + "ism@kbs.co.kr\r\n"
			+ "2017-03-17\r\n" + "KBS\r\n" + "김선영\r\n" + "기자\r\n" + "사회\r\n" + "wake@kbs.co.kr\r\n" + "2017-02-06\r\n"
			+ "KBS\r\n" + "김민아\r\n" + "기자\r\n" + "사회\r\n" + "kma@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n"
			+ "이만영\r\n" + "기자\r\n" + "사회\r\n" + "2man0@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김효신\r\n"
			+ "기자\r\n" + "사회\r\n" + "shiny33@kbs.co.kr\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "최선중\r\n" + "기자\r\n"
			+ "사회\r\n" + "best-ing@kbs.co.kr\r\n" + "2017-03-04\r\n" + "KBS\r\n" + "류해남\r\n" + "기자\r\n" + "사회\r\n"
			+ "banny@kbs.co.kr\r\n" + "2016-10-15\r\n" + "KBS\r\n" + "곽선정\r\n" + "기자\r\n" + "사회\r\n"
			+ "coolsun@kbs.co.kr\r\n" + "2017-03-12\r\n" + "KBS\r\n" + "이승재\r\n" + "기자\r\n" + "사회\r\n"
			+ "sjl@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "유승용\r\n" + "기자\r\n" + "사회\r\n"
			+ "hara1848@kbs.co.kr\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "유진휘\r\n" + "기자\r\n" + "사회\r\n"
			+ "yujh@kbs.co.kr\r\n" + "2017-02-01\r\n" + "KBS\r\n" + "송승룡\r\n" + "기자\r\n" + "사회\r\n"
			+ "oberona@kbs.co.kr\r\n" + "2017-03-24\r\n" + "KBS\r\n" + "신주현\r\n" + "기자\r\n" + "사회\r\n"
			+ "shinjour@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "박상현\r\n" + "기자\r\n" + "사회\r\n"
			+ "sanghyun@kbs.co.kr\r\n" + "2017-03-12\r\n" + "KBS\r\n" + "이민우\r\n" + "기자\r\n" + "사회\r\n"
			+ "minoo@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "이화연\r\n" + "기자\r\n" + "사회\r\n"
			+ "yeon@kbs.co.kr\r\n" + "2017-02-06\r\n" + "KBS\r\n" + "박상용\r\n" + "기자\r\n" + "사회\r\n"
			+ "miso@kbs.co.kr\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "김소영\r\n" + "기자\r\n" + "사회\r\n"
			+ "kantapia@kbs.co.kr\r\n" + "2017-02-15\r\n" + "KBS\r\n" + "이슬기\r\n" + "기자\r\n" + "사회\r\n"
			+ "wakeup@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "박익원\r\n" + "기자\r\n" + "사회\r\n"
			+ "iwpark@kbs.co.kr\r\n" + "2016-11-27\r\n" + "KBS\r\n" + "정창환\r\n" + "기자\r\n" + "사회\r\n"
			+ "hwan0201@kbs.co.kr\r\n" + "2017-02-01\r\n" + "KBS\r\n" + "하무림\r\n" + "기자\r\n" + "사회\r\n"
			+ "hagosu@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "박재홍\r\n" + "기자\r\n" + "사회\r\n"
			+ "pressp@kbs.co.kr\r\n" + "2017-01-08\r\n" + "KBS\r\n" + "신지원\r\n" + "기자\r\n" + "사회\r\n"
			+ "4you@kbs.co.kr\r\n" + "2017-03-03\r\n" + "KBS\r\n" + "송영석\r\n" + "기자\r\n" + "사회\r\n"
			+ "sys@kbs.co.kr\r\n" + "2016-10-29\r\n" + "KBS\r\n" + "김명주\r\n" + "기자\r\n" + "사회\r\n"
			+ "silk@kbs.co.kr\r\n" + "2017-02-14\r\n" + "KBS\r\n" + "이정훈\r\n" + "기자\r\n" + "사회\r\n"
			+ "hwarang08@kbs.co.kr\r\n" + "2017-02-04\r\n" + "KBS\r\n" + "김대영\r\n" + "기자\r\n" + "사회\r\n"
			+ "kiza@kbs.co.kr\r\n" + "2017-03-26\r\n" + "KBS\r\n" + "우동윤\r\n" + "기자\r\n" + "사회\r\n"
			+ "seagarden@kbs.co.kr\r\n" + "2017-03-05\r\n" + "KBS\r\n" + "김덕원\r\n" + "기자\r\n" + "사회\r\n"
			+ "kim0526@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "황상길\r\n" + "기자\r\n" + "사회\r\n"
			+ "hskil@kbs.co.kr\r\n" + "2017-02-23\r\n" + "KBS\r\n" + "강규엽\r\n" + "기자\r\n" + "사회\r\n"
			+ "basic@kbs.co.kr\r\n" + "2016-12-19\r\n" + "KBS\r\n" + "정현숙\r\n" + "기자\r\n" + "사회\r\n"
			+ "hyensui@kbs.co.kr\r\n" + "2016-11-19\r\n" + "KBS\r\n" + "강수정\r\n" + "기자\r\n" + "사회\r\n"
			+ "kkangsoo83@kbs.co.kr\r\n" + "2016-11-01\r\n" + "KBS\r\n" + "이화진\r\n" + "기자\r\n" + "사회\r\n"
			+ "hosky@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "박선자\r\n" + "기자\r\n" + "사회\r\n"
			+ "psj30@kbs.co.kr\r\n" + "2017-02-19\r\n" + "KBS\r\n" + "한성원\r\n" + "기자\r\n" + "사회\r\n"
			+ "hansw@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "김문영\r\n" + "기자\r\n" + "사회\r\n"
			+ "mykim@kbs.co.kr\r\n" + "2017-02-04\r\n" + "KBS\r\n" + "최세진\r\n" + "기자\r\n" + "사회\r\n"
			+ "cejine@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "함영구\r\n" + "기자\r\n" + "사회\r\n"
			+ "newspower@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김범주\r\n" + "기자\r\n" + "사회\r\n"
			+ "category@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "채승민\r\n" + "기자\r\n" + "사회\r\n"
			+ "smchae@kbs.co.kr\r\n" + "2017-03-04\r\n" + "KBS\r\n" + "최은진\r\n" + "기자\r\n" + "사회\r\n"
			+ "ejch@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "사정원\r\n" + "기자\r\n" + "사회\r\n"
			+ "jwsa@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "정재준\r\n" + "기자\r\n" + "사회\r\n"
			+ "jjjeong@kbs.co.kr\r\n" + "2016-11-08\r\n" + "KBS\r\n" + "한승연\r\n" + "기자\r\n" + "사회\r\n"
			+ "hanspond@kbs.co.kr\r\n" + "2017-03-14\r\n" + "KBS\r\n" + "송현준\r\n" + "기자\r\n" + "사회\r\n"
			+ "horrorlong@kbs.co.kr\r\n" + "2016-11-16\r\n" + "KBS\r\n" + "김현수\r\n" + "기자\r\n" + "사회\r\n"
			+ "kimhs@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "천춘환\r\n" + "기자\r\n" + "사회\r\n"
			+ "southpaw@kbs.co.kr\r\n" + "2017-02-23\r\n" + "KBS\r\n" + "박미영\r\n" + "기자\r\n" + "사회\r\n"
			+ "mypark@kbs.co.kr\r\n" + "2017-03-20\r\n" + "KBS\r\n" + "박장훈\r\n" + "기자\r\n" + "사회\r\n"
			+ "pjh@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "배병오\r\n" + "기자\r\n" + "사회\r\n"
			+ "cueb@kbs.co.kr\r\n" + "2016-11-12\r\n" + "KBS\r\n" + "서승신\r\n" + "기자\r\n" + "사회\r\n"
			+ "sss4854@kbs.co.kr\r\n" + "2017-03-06\r\n" + "KBS\r\n" + "조영호\r\n" + "기자\r\n" + "사회\r\n"
			+ "new3014@kbs.co.kr\r\n" + "2016-11-26\r\n" + "KBS\r\n" + "복창현\r\n" + "기자\r\n" + "사회\r\n"
			+ "changhyun@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "조연주\r\n" + "기자\r\n" + "사회\r\n"
			+ "yeonjoo@kbs.co.kr\r\n" + "2017-02-06\r\n" + "KBS\r\n" + "조선우\r\n" + "기자\r\n" + "사회\r\n"
			+ "ssun@kbs.co.kr\r\n" + "2017-02-24\r\n" + "KBS\r\n" + "윤봄이\r\n" + "기자\r\n" + "사회\r\n"
			+ "springyoon@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김광진\r\n" + "기자\r\n" + "사회\r\n"
			+ "powjnl@kbs.co.kr\r\n" + "2016-12-30\r\n" + "KBS\r\n" + "지창환\r\n" + "기자\r\n" + "사회\r\n"
			+ "2su3san@kbs.co.kr\r\n" + "2016-11-21\r\n" + "KBS\r\n" + "강전일\r\n" + "기자\r\n" + "사회\r\n"
			+ "korkang@kbs.co.kr\r\n" + "2016-11-24\r\n" + "KBS\r\n" + "엄기숙\r\n" + "기자\r\n" + "사회\r\n"
			+ "hotpencil@kbs.co.kr\r\n" + "2017-02-05\r\n" + "KBS\r\n" + "조정아\r\n" + "기자\r\n" + "사회\r\n"
			+ "right@kbs.co.kr\r\n" + "2017-03-17\r\n" + "KBS\r\n" + "이재민\r\n" + "기자\r\n" + "사회\r\n"
			+ "truepen@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "김종환\r\n" + "기자\r\n" + "사회\r\n"
			+ "kjh@kbs.co.kr\r\n" + "2016-11-29\r\n" + "KBS\r\n" + "김석\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "stone21@kbs.co.kr\r\n" + "2017-02-24\r\n" + "KBS\r\n" + "송명훈\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "smh@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "계현우\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "kye@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "윤성욱\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "mediaeye@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "이호을\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "helee@kbs.co.kr\r\n" + "2016-06-02\r\n" + "KBS\r\n" + "김민경\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "mkdream@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "이경진\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "taas@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "김방홍\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "kbh0428@kbs.co.kr\r\n" + "2017-03-15\r\n" + "KBS\r\n" + "심연희\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "simony@kbs.co.kr\r\n" + "2016-12-06\r\n" + "KBS\r\n" + "김빛이라\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "glory@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김주한\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "telecaster@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "용태영\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "yongty@kbs.co.kr\r\n" + "2017-03-26\r\n" + "KBS\r\n" + "박영하\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "ha93@kbs.co.kr\r\n" + "2017-02-24\r\n" + "KBS\r\n" + "윤수희\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "shy@kbs.co.kr\r\n" + "2017-02-19\r\n" + "KBS\r\n" + "이영진\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "yjlee@kbs.co.kr\r\n" + "2016-12-13\r\n" + "KBS\r\n" + "박수현\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "supak@kbs.co.kr\r\n" + "2016-12-18\r\n" + "KBS\r\n" + "서영민\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "seo0177@gmail.com\r\n" + "2017-03-06\r\n" + "KBS\r\n" + "선재희\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "ana@kbs.co.kr\r\n" + "2016-11-25\r\n" + "KBS\r\n" + "하준수\r\n" + "특파원\r\n" + "생활/문화\r\n"
			+ "ha6666js@kbs.co.kr\r\n" + "2017-03-28\r\n" + "KBS\r\n" + "박영관\r\n" + "특파원\r\n" + "생활/문화\r\n"
			+ "pyk091@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김태욱\r\n" + "특파원\r\n" + "생활/문화\r\n"
			+ "twkim@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "정새배\r\n" + "기자\r\n" + "세계\r\n"
			+ "newboat@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김의철\r\n" + "기자\r\n" + "세계\r\n"
			+ "kimec@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "서지영\r\n" + "기자\r\n" + "세계\r\n"
			+ "sjy@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "백진원\r\n" + "기자\r\n" + "세계\r\n"
			+ "jwhite@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김성모\r\n" + "기자\r\n" + "세계\r\n"
			+ "ksm@kbs.co.kr\r\n" + "2016-08-10\r\n" + "KBS\r\n" + "허솔지\r\n" + "기자\r\n" + "세계\r\n"
			+ "solji26@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "윤상\r\n" + "기자\r\n" + "세계\r\n"
			+ "yoonsang@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "이진성\r\n" + "기자\r\n" + "세계\r\n"
			+ "e-gija@kbs.co.kr\r\n" + "2017-03-03\r\n" + "KBS\r\n" + "고아름\r\n" + "기자\r\n" + "세계\r\n"
			+ "areum@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김시원\r\n" + "기자\r\n" + "세계\r\n"
			+ "siwon@kbs.co.kr\r\n" + "2016-07-09\r\n" + "KBS\r\n" + "이재석\r\n" + "기자\r\n" + "세계\r\n"
			+ "jaeseok@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "최성원\r\n" + "기자\r\n" + "세계\r\n"
			+ "swchoi@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김영은\r\n" + "기자\r\n" + "세계\r\n"
			+ "paz@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "정재우\r\n" + "기자\r\n" + "세계\r\n" + "jjw@kbs.co.kr\r\n"
			+ "2017-03-15\r\n" + "KBS\r\n" + "박에스더\r\n" + "기자\r\n" + "세계\r\n" + "stellar@kbs.co.kr\r\n"
			+ "2017-04-01\r\n" + "KBS\r\n" + "오세균\r\n" + "기자\r\n" + "세계\r\n" + "sko@kbs.co.kr\r\n" + "2017-04-01\r\n"
			+ "KBS\r\n" + "나신하\r\n" + "기자\r\n" + "세계\r\n" + "daniel@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n"
			+ "이정민\r\n" + "기자\r\n" + "세계\r\n" + "mani@kbs.co.kr\r\n" + "2016-07-07\r\n" + "KBS\r\n" + "윤석구\r\n"
			+ "기자\r\n" + "세계\r\n" + "sukkoo@kbs.co.kr\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "양영은\r\n" + "기자\r\n"
			+ "세계\r\n" + "yeyang@kbs.co.kr\r\n" + "2017-03-21\r\n" + "KBS\r\n" + "유동엽\r\n" + "기자\r\n" + "세계\r\n"
			+ "imhere@kbs.co.kr\r\n" + "2017-03-27\r\n" + "KBS\r\n" + "박진현\r\n" + "기자\r\n" + "세계\r\n"
			+ "parkjh@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "송명희\r\n" + "기자\r\n" + "세계\r\n"
			+ "thimble@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "김재현\r\n" + "기자\r\n" + "세계\r\n"
			+ "honor@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "이승준\r\n" + "기자\r\n" + "세계\r\n"
			+ "sailing@kbs.co.kr\r\n" + "2016-12-07\r\n" + "KBS\r\n" + "이승철\r\n" + "기자\r\n" + "세계\r\n"
			+ "neost@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김덕훈\r\n" + "기자\r\n" + "세계\r\n"
			+ "standby@kbs.co.kr\r\n" + "2017-03-16\r\n" + "KBS\r\n" + "김진호\r\n" + "기자\r\n" + "세계\r\n"
			+ "hit@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "박현\r\n" + "기자\r\n" + "세계\r\n" + "why@kbs.co.kr\r\n"
			+ "2016-12-11\r\n" + "KBS\r\n" + "조지현\r\n" + "기자\r\n" + "세계\r\n" + "cho2008@kbs.co.kr\r\n"
			+ "2017-03-31\r\n" + "KBS\r\n" + "이광열\r\n" + "기자\r\n" + "세계\r\n" + "the12th@kbs.co.kr\r\n"
			+ "2017-02-22\r\n" + "KBS\r\n" + "박찬형\r\n" + "기자\r\n" + "세계\r\n" + "parkchan@kbs.co.kr\r\n"
			+ "2016-10-13\r\n" + "KBS\r\n" + "김진우\r\n" + "기자\r\n" + "세계\r\n" + "kjinwoo@kbs.co.kr\r\n"
			+ "2017-03-31\r\n" + "KBS\r\n" + "조은경\r\n" + "기자\r\n" + "세계\r\n" + "eunkungcho@kbs.co.kr\r\n"
			+ "2016-11-07\r\n" + "KBS\r\n" + "노태영\r\n" + "기자\r\n" + "세계\r\n" + "lotte0@kbs.co.kr\r\n" + "2017-01-16\r\n"
			+ "KBS\r\n" + "구본국\r\n" + "기자\r\n" + "세계\r\n" + "bkku@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n"
			+ "황현택\r\n" + "기자\r\n" + "세계\r\n" + "news1@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "김환주\r\n"
			+ "기자\r\n" + "세계\r\n" + "towndrum@kbs.co.kr\r\n" + "2017-03-22\r\n" + "KBS\r\n" + "양성모\r\n" + "기자\r\n"
			+ "세계\r\n" + "ysm80@kbs.co.kr\r\n" + "2017-02-07\r\n" + "KBS\r\n" + "최광호\r\n" + "기자\r\n" + "세계\r\n"
			+ "peace@kbs.co.kr\r\n" + "2017-03-01\r\n" + "KBS\r\n" + "이재원\r\n" + "기자\r\n" + "세계\r\n"
			+ "ljw@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "김연주\r\n" + "기자\r\n" + "세계\r\n"
			+ "mint@kbs.co.kr\r\n" + "2016-10-29\r\n" + "KBS\r\n" + "최형원\r\n" + "기자\r\n" + "세계\r\n"
			+ "roediec@kbs.co.kr\r\n" + "2017-01-08\r\n" + "KBS\r\n" + "이근우\r\n" + "기자\r\n" + "세계\r\n"
			+ "lkw@kbs.co.kr\r\n" + "2016-12-18\r\n" + "KBS\r\n" + "김종수\r\n" + "기자\r\n" + "세계\r\n"
			+ "sweeper@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "백운기\r\n" + "기자\r\n" + "세계\r\n"
			+ "thenews@kbs.co.kr\r\n" + "2017-02-07\r\n" + "KBS\r\n" + "강재훈\r\n" + "기자\r\n" + "세계\r\n"
			+ "bahn@kbs.co.kr\r\n" + "2017-02-17\r\n" + "KBS\r\n" + "이민우\r\n" + "특파원\r\n" + "세계\r\n"
			+ "tspark@kbs.co.kr\r\n" + "2017-03-11\r\n" + "KBS\r\n" + "전종철\r\n" + "특파원\r\n" + "세계\r\n"
			+ "jcj@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김범수\r\n" + "기자\r\n" + "인터넷/SNS\r\n"
			+ "recruit@yjmgames.com\r\n" + "2016-10-12\r\n" + "KBS\r\n" + "정연우\r\n" + "기자\r\n" + "정치\r\n"
			+ "nforyou@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김병용\r\n" + "기자\r\n" + "정치\r\n"
			+ "kby@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "김경수\r\n" + "기자\r\n" + "정치\r\n"
			+ "bada@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "류호성\r\n" + "기자\r\n" + "정치\r\n"
			+ "ryuhs@kbs.co.kr\r\n" + "2017-03-22\r\n" + "KBS\r\n" + "홍혜림\r\n" + "기자\r\n" + "정치\r\n"
			+ "newshong@kbs.co.kr\r\n" + "2016-07-14\r\n" + "KBS\r\n" + "최동혁\r\n" + "기자\r\n" + "정치\r\n"
			+ "vivadong@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "강나루\r\n" + "기자\r\n" + "정치\r\n"
			+ "naru@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김희용\r\n" + "기자\r\n" + "정치\r\n"
			+ "emaninny@kbs.co.kr\r\n" + "2017-01-14\r\n" + "KBS\r\n" + "장덕수\r\n" + "기자\r\n" + "정치\r\n"
			+ "joannes@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "고은희\r\n" + "기자\r\n" + "정치\r\n"
			+ "ginger@kbs.co.kr\r\n" + "2017-02-21\r\n" + "KBS\r\n" + "유광석\r\n" + "기자\r\n" + "정치\r\n"
			+ "ksyoo@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "조빛나\r\n" + "기자\r\n" + "정치\r\n"
			+ "hymn@kbs.co.kr\r\n" + "2017-02-22\r\n" + "KBS\r\n" + "김지숙\r\n" + "기자\r\n" + "정치\r\n"
			+ "jskim84@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "신지혜\r\n" + "기자\r\n" + "정치\r\n"
			+ "new@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "김학재\r\n" + "기자\r\n" + "정치\r\n"
			+ "windows@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "남승우\r\n" + "기자\r\n" + "정치\r\n"
			+ "futurist@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "정성호\r\n" + "기자\r\n" + "정치\r\n"
			+ "andreas@kbs.co.kr\r\n" + "2016-06-11\r\n" + "KBS\r\n" + "황진우\r\n" + "기자\r\n" + "정치\r\n"
			+ "simon@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "조성원\r\n" + "기자\r\n" + "정치\r\n"
			+ "sungwonc@kbs.co.kr\r\n" + "2017-03-04\r\n" + "KBS\r\n" + "서병립\r\n" + "기자\r\n" + "정치\r\n"
			+ "realist@kbs.co.kr\r\n" + "2016-12-03\r\n" + "KBS\r\n" + "허효진\r\n" + "기자\r\n" + "정치\r\n"
			+ "her@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "정아연\r\n" + "기자\r\n" + "정치\r\n"
			+ "niche@kbs.co.kr\r\n" + "2017-04-01\r\n" + "KBS\r\n" + "정인성\r\n" + "기자\r\n" + "정치\r\n"
			+ "chungis@kbs.co.kr\r\n" + "2017-03-23\r\n" + "KBS\r\n" + "김용준\r\n" + "기자\r\n" + "정치\r\n"
			+ "okok@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "김기흥\r\n" + "기자\r\n" + "정치\r\n"
			+ "heung@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "소현정\r\n" + "기자\r\n" + "정치\r\n"
			+ "shj204@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "구경하\r\n" + "기자\r\n" + "정치\r\n"
			+ "isegoria@kbs.co.kr\r\n" + "2017-03-31\r\n" + "KBS\r\n" + "이주한\r\n" + "기자\r\n" + "정치\r\n"
			+ "juhan@kbs.co.kr\r\n" + "2016-12-15\r\n" + "KBS\r\n" + "김지숙\r\n" + "기자\r\n" + "정치\r\n"
			+ "jin@kbs.co.kr\r\n" + "2017-03-30\r\n" + "KBS\r\n" + "이효용\r\n" + "기자\r\n" + "정치\r\n"
			+ "utility@kbs.co.kr\r\n" + "2017-03-05\r\n" + "KBS\r\n" + "백인순\r\n" + "기자\r\n" + "정치\r\n"
			+ "insoon@kbs.co.kr\r\n" + "2017-03-29\r\n" + "KBS\r\n" + "최규식\r\n" + "기자\r\n" + "정치\r\n"
			+ "kyoosik@kbs.co.kr\r\n" + "2017-01-15\r\n" + "KBS\r\n" + "이석호\r\n" + "기자\r\n" + "정치\r\n"
			+ "leesukho@kbs.co.kr\r\n" + "2017-01-01\r\n" + "KBS\r\n" + "최재현\r\n" + "기자\r\n" + "정치\r\n"
			+ "jaychoy@kbs.co.kr\r\n" + "2016-10-24\r\n" + "KBS\r\n" + "이강덕\r\n" + "기자\r\n" + "정치\r\n"
			+ "kdlee@kbs.co.kr\r\n" + "2017-03-25\r\n" + "KBS\r\n" + "김도엽\r\n" + "특파원\r\n" + "정치\r\n"
			+ "yop21@kbs.co.kr\r\n" + "2017-03-28\r\n" + "MBC\r\n" + "조현용\r\n" + "기자\r\n" + "IT\r\n"
			+ "star@mbc.co.kr\r\n" + "2017-03-30\r\n" + "MBC\r\n" + "전종환\r\n" + "기자\r\n" + "건강\r\n"
			+ "wari99@mbc.co.kr\r\n" + "2017-03-26\r\n" + "MBC\r\n" + "박민주\r\n" + "기자\r\n" + "경제\r\n"
			+ "minju@imbc.com\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "김성민\r\n" + "기자\r\n" + "경제\r\n"
			+ "smile21@mbc.co.kr\r\n" + "2017-03-07\r\n" + "MBC\r\n" + "이준범\r\n" + "기자\r\n" + "경제\r\n"
			+ "ljoonb@mbc.co.kr\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "손병산\r\n" + "기자\r\n" + "경제\r\n"
			+ "san@mbc.co.kr\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "장현주\r\n" + "기자\r\n" + "경제\r\n"
			+ "hjang@mbc.co.kr\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "오상연\r\n" + "기자\r\n" + "경제\r\n"
			+ "art@mbc.co.kr\r\n" + "2017-03-22\r\n" + "MBC\r\n" + "전준홍\r\n" + "기자\r\n" + "경제\r\n"
			+ "jjhong@mbc.co.kr\r\n" + "2017-03-07\r\n" + "MBC\r\n" + "염규현\r\n" + "기자\r\n" + "경제\r\n"
			+ "email@mbc.co.kr\r\n" + "2017-03-27\r\n" + "MBC\r\n" + "김세의\r\n" + "기자\r\n" + "경제\r\n"
			+ "coach43@imbc.com\r\n" + "2017-03-25\r\n" + "MBC\r\n" + "김장훈\r\n" + "기자\r\n" + "경제\r\n"
			+ "cooldude@mbc.co.kr\r\n" + "2017-03-14\r\n" + "MBC\r\n" + "이정신\r\n" + "기자\r\n" + "경제\r\n"
			+ "geist1@imbc.com\r\n" + "2017-01-04\r\n" + "MBC\r\n" + "박영회\r\n" + "기자\r\n" + "경제\r\n"
			+ "salto@mbc.co.kr\r\n" + "2017-03-20\r\n" + "MBC\r\n" + "이상민\r\n" + "기자\r\n" + "경제\r\n"
			+ "mini4173@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "장유진\r\n" + "기자\r\n" + "경제\r\n"
			+ "jjangjjang@mbc.co.kr\r\n" + "2017-03-20\r\n" + "MBC\r\n" + "정재윤\r\n" + "기자\r\n" + "경제\r\n"
			+ "jjung@mbc.co.kr\r\n" + "2017-03-24\r\n" + "MBC\r\n" + "전예지\r\n" + "기자\r\n" + "경제\r\n"
			+ "yeji@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "정동훈\r\n" + "기자\r\n" + "경제\r\n"
			+ "jdh@mbc.co.kr\r\n" + "2017-03-02\r\n" + "MBC\r\n" + "전동혁\r\n" + "기자\r\n" + "경제\r\n" + "dhj@mbc.co.kr\r\n"
			+ "2017-03-30\r\n" + "MBC\r\n" + "지영은\r\n" + "기자\r\n" + "경제\r\n" + "ychi@mbc.co.kr\r\n" + "2017-03-31\r\n"
			+ "MBC\r\n" + "조영무\r\n" + "연구위원\r\n" + "경제\r\n" + "forpeople@imbc.com\r\n" + "2017-03-25\r\n" + "MBC\r\n"
			+ "양효걸\r\n" + "기자\r\n" + "도로/교통\r\n" + "amadeus@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "김수정\r\n"
			+ "기자\r\n" + "도로/교통\r\n" + "kimsj@imbc.com\r\n" + "2016-07-07\r\n" + "MBC\r\n" + "나세웅\r\n" + "기자\r\n"
			+ "도로/교통\r\n" + "nofootbird@mbc.co.kr\r\n" + "2016-07-07\r\n" + "MBC\r\n" + "임경아\r\n" + "기자\r\n"
			+ "도로/교통\r\n" + "iamhere@mbc.co.kr\r\n" + "2017-03-26\r\n" + "MBC\r\n" + "여홍규\r\n" + "기자\r\n" + "사회\r\n"
			+ "yhg@mbc.co.kr\r\n" + "2016-05-31\r\n" + "MBC\r\n" + "이성일\r\n" + "기자\r\n" + "사회\r\n"
			+ "silee@mbc.co.kr\r\n" + "2017-03-02\r\n" + "MBC\r\n" + "김나라\r\n" + "기자\r\n" + "사회\r\n"
			+ "flara@mbc.co.kr\r\n" + "2016-08-19\r\n" + "MBC\r\n" + "이학수\r\n" + "기자\r\n" + "사회\r\n"
			+ "tchain@mbc.co.kr\r\n" + "2017-03-03\r\n" + "MBC\r\n" + "오현석\r\n" + "기자\r\n" + "사회\r\n"
			+ "ohs@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "전봉기\r\n" + "기자\r\n" + "사회\r\n"
			+ "leadship@imbc.com\r\n" + "2017-03-26\r\n" + "MBC\r\n" + "남재현\r\n" + "기자\r\n" + "사회\r\n"
			+ "now@mbc.co.kr\r\n" + "2017-02-08\r\n" + "MBC\r\n" + "박성원\r\n" + "기자\r\n" + "사회\r\n"
			+ "want@mbc.co.kr\r\n" + "2017-03-24\r\n" + "MBC\r\n" + "김나리\r\n" + "기자\r\n" + "사회\r\n"
			+ "narikim@mbc.co.kr\r\n" + "2016-10-31\r\n" + "MBC\r\n" + "윤성철\r\n" + "기자\r\n" + "사회\r\n"
			+ "ysc@mbc.co.kr\r\n" + "2017-03-06\r\n" + "MBC\r\n" + "박주린\r\n" + "기자\r\n" + "사회\r\n"
			+ "lovepark@mbc.co.kr\r\n" + "2017-02-16\r\n" + "MBC\r\n" + "전기영\r\n" + "기자\r\n" + "사회\r\n"
			+ "niceman@mbc.co.kr\r\n" + "2017-03-22\r\n" + "MBC\r\n" + "김진희\r\n" + "기자\r\n" + "사회\r\n"
			+ "lamp@mbc.co.kr\r\n" + "2017-03-07\r\n" + "MBC\r\n" + "조국현\r\n" + "기자\r\n" + "사회\r\n"
			+ "jojo@mbc.co.kr\r\n" + "2016-12-22\r\n" + "MBC\r\n" + "전재홍\r\n" + "기자\r\n" + "사회\r\n"
			+ "bobo@mbc.co.kr\r\n" + "2017-01-15\r\n" + "MBC\r\n" + "박준규\r\n" + "기자\r\n" + "사회\r\n"
			+ "jpark@mbc.co.kr\r\n" + "2017-03-22\r\n" + "MBC\r\n" + "이동경\r\n" + "기자\r\n" + "사회\r\n"
			+ "tokyo@mbc.co.kr\r\n" + "2017-03-04\r\n" + "MBC\r\n" + "홍신영\r\n" + "기자\r\n" + "사회\r\n"
			+ "hsy@mbc.co.kr\r\n" + "2017-03-21\r\n" + "MBC\r\n" + "송양환\r\n" + "기자\r\n" + "사회\r\n"
			+ "rainbow@mbc.co.kr\r\n" + "2017-03-11\r\n" + "MBC\r\n" + "류병수\r\n" + "기자\r\n" + "사회\r\n"
			+ "gamja@mbc.co.kr\r\n" + "2017-02-23\r\n" + "MBC\r\n" + "홍승욱\r\n" + "기자\r\n" + "사회\r\n"
			+ "hongs@mbc.co.kr\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "조윤정\r\n" + "기자\r\n" + "사회\r\n"
			+ "cyjung@imbc.com\r\n" + "2017-03-25\r\n" + "MBC\r\n" + "김준형\r\n" + "기자\r\n" + "사회\r\n"
			+ "bluewave7@mbc.co.kr\r\n" + "2017-03-30\r\n" + "MBC\r\n" + "이덕영\r\n" + "기자\r\n" + "사회\r\n"
			+ "deok@mbc.co.kr\r\n" + "2017-01-09\r\n" + "MBC\r\n" + "김미희\r\n" + "기자\r\n" + "사회\r\n"
			+ "bravemh@imbc.com\r\n" + "2017-03-26\r\n" + "MBC\r\n" + "백연상\r\n" + "기자\r\n" + "사회\r\n"
			+ "paik@mbc.co.kr\r\n" + "2017-03-02\r\n" + "MBC\r\n" + "오유림\r\n" + "기자\r\n" + "사회\r\n"
			+ "yroh@mbc.co.kr\r\n" + "2017-03-16\r\n" + "MBC\r\n" + "김소영\r\n" + "기자\r\n" + "사회\r\n"
			+ "acacia@imbc.com\r\n" + "2016-11-25\r\n" + "MBC\r\n" + "공보영\r\n" + "기자\r\n" + "사회\r\n"
			+ "bobob@mbc.co.kr\r\n" + "2016-11-28\r\n" + "MBC\r\n" + "이경미\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "light@mbc.co.kr\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "조윤미\r\n" + "기자\r\n" + "생활경제\r\n"
			+ "bongbong@mbc.co.kr\r\n" + "2017-03-28\r\n" + "MBC\r\n" + "박새암\r\n" + "기자\r\n" + "세계\r\n"
			+ "sammy.park@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "장미일\r\n" + "기자\r\n" + "세계\r\n"
			+ "meal@imbc.com\r\n" + "2017-03-27\r\n" + "MBC\r\n" + "정시내\r\n" + "기자\r\n" + "세계\r\n"
			+ "stream@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "박영일\r\n" + "기자\r\n" + "세계\r\n"
			+ "parkyi75@imbc.com\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "박상후\r\n" + "기자\r\n" + "세계\r\n"
			+ "pushangh@imbc.com\r\n" + "2016-08-09\r\n" + "MBC\r\n" + "허지은\r\n" + "기자\r\n" + "세계\r\n"
			+ "kldream@imbc.com\r\n" + "2017-02-21\r\n" + "MBC\r\n" + "한동수\r\n" + "기자\r\n" + "세계\r\n"
			+ "dshan@imbc.com\r\n" + "2017-02-05\r\n" + "MBC\r\n" + "남상호\r\n" + "기자\r\n" + "세계\r\n"
			+ "fatshady@imbc.com\r\n" + "2016-11-18\r\n" + "MBC\r\n" + "민경의\r\n" + "기자\r\n" + "세계\r\n"
			+ "justice@imbc.com\r\n" + "2016-11-25\r\n" + "MBC\r\n" + "박범수\r\n" + "특파원\r\n" + "세계\r\n"
			+ "bspark@imbc.com\r\n" + "2016-07-07\r\n" + "MBC\r\n" + "전재호\r\n" + "특파원\r\n" + "세계\r\n"
			+ "onyou@mbc.co.kr\r\n" + "2017-03-24\r\n" + "MBC\r\n" + "금기종\r\n" + "특파원\r\n" + "세계\r\n"
			+ "kum2001@imbc.com\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "이동애\r\n" + "특파원\r\n" + "세계\r\n"
			+ "leeda@imbc.com\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "박승진\r\n" + "특파원\r\n" + "세계\r\n"
			+ "sjpark@imbc.com\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "권순표\r\n" + "특파원\r\n" + "세계\r\n"
			+ "kspja@imbc.com\r\n" + "2016-12-24\r\n" + "MBC\r\n" + "이언주\r\n" + "특파원\r\n" + "세계\r\n"
			+ "unjoolee@imbc.com\r\n" + "2016-06-10\r\n" + "MBC\r\n" + "서민수\r\n" + "특파원\r\n" + "세계\r\n"
			+ "minsoo@imbc.com\r\n" + "2017-03-30\r\n" + "MBC\r\n" + "이주훈\r\n" + "특파원\r\n" + "세계\r\n"
			+ "june@imbc.com\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "이주승\r\n" + "특파원\r\n" + "세계\r\n"
			+ "jason@imbc.com\r\n" + "2017-02-21\r\n" + "MBC\r\n" + "고주룡\r\n" + "특파원\r\n" + "세계\r\n"
			+ "jrko@imbc.com\r\n" + "2016-07-08\r\n" + "MBC\r\n" + "김필국\r\n" + "특파원\r\n" + "세계\r\n"
			+ "philh@imbc.com\r\n" + "2017-03-28\r\n" + "MBC\r\n" + "김연석\r\n" + "특파원\r\n" + "세계\r\n"
			+ "yeonsug@imbc.com\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "이진희\r\n" + "특파원\r\n" + "세계\r\n"
			+ "jhlee@imbc.com\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "박상규\r\n" + "기자\r\n" + "정치\r\n"
			+ "sgpark39@gmail.com\r\n" + "2017-03-30\r\n" + "MBC\r\n" + "구경근\r\n" + "기자\r\n" + "정치\r\n"
			+ "kpluskk@mbc.co.kr\r\n" + "2017-03-29\r\n" + "MBC\r\n" + "조영익\r\n" + "기자\r\n" + "정치\r\n"
			+ "cyi@mbc.co.kr\r\n" + "2017-03-27\r\n" + "MBC\r\n" + "오해정\r\n" + "기자\r\n" + "정치\r\n" + "why@mbc.co.kr\r\n"
			+ "2016-11-10\r\n" + "MBC\r\n" + "박성준\r\n" + "기자\r\n" + "정치\r\n" + "glory@imbc.com\r\n" + "2017-03-01\r\n"
			+ "MBC\r\n" + "장승철\r\n" + "기자\r\n" + "정치\r\n" + "sunysb@mbc.co.kr\r\n" + "2017-03-11\r\n" + "MBC\r\n"
			+ "현원섭\r\n" + "기자\r\n" + "정치\r\n" + "hyunny@mbc.co.kr\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "김세진\r\n"
			+ "기자\r\n" + "정치\r\n" + "blue32@mbc.co.kr\r\n" + "2017-03-10\r\n" + "MBC\r\n" + "이준희\r\n" + "기자\r\n"
			+ "정치\r\n" + "letswin@mbc.co.kr\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "손령\r\n" + "기자\r\n" + "정치\r\n"
			+ "right@mbc.co.kr\r\n" + "2017-03-11\r\n" + "MBC\r\n" + "김정호\r\n" + "기자\r\n" + "정치\r\n"
			+ "apro@imbc.com\r\n" + "2017-03-16\r\n" + "MBC\r\n" + "조재영\r\n" + "기자\r\n" + "정치\r\n"
			+ "jojae@mbc.co.kr\r\n" + "2017-03-31\r\n" + "MBC\r\n" + "박상권\r\n" + "기자\r\n" + "정치\r\n"
			+ "skpark@imbc.com\r\n" + "2016-10-15\r\n" + "MBC\r\n" + "현재근\r\n" + "기자\r\n" + "정치\r\n"
			+ "jkhyun@mbc.co.kr\r\n" + "2017-04-01\r\n" + "MBC\r\n" + "노재필\r\n" + "기자\r\n" + "정치\r\n"
			+ "jaepil@imbc.com\r\n" + "2017-03-02\r\n" + "MBC\r\n" + "이재민\r\n" + "기자\r\n" + "정치\r\n"
			+ "epic@mbc.co.kr\r\n" + "2017-03-27\r\n" + "MBC\r\n" + "정병화\r\n" + "기자\r\n" + "정치\r\n"
			+ "chungspeak@mbc.co.kr\r\n" + "2017-03-27\r\n" + "MBC\r\n" + "김지경\r\n" + "기자\r\n" + "환경\r\n"
			+ "ivot@imbc.com\r\n" + "2016-10-13\r\n" + "MBN\r\n" + "서주영\r\n" + "기자\r\n" + "글로벌경제\r\n"
			+ "juleseo@mbn.co.kr\r\n" + "2016-11-17\r\n" + "MBN\r\n" + "이상주\r\n" + "기자\r\n" + "글로벌경제\r\n"
			+ "mbn27@naver.com\r\n" + "2017-03-23\r\n" + "MBN\r\n" + "연장현\r\n" + "기자\r\n" + "도로/교통\r\n"
			+ "tallyeon@mbn.co.kr\r\n" + "2016-06-22\r\n" + "MBN\r\n" + "노승환\r\n" + "기자\r\n" + "미국/중남미\r\n"
			+ "todif77@mbn.co.kr\r\n" + "2016-10-15\r\n" + "MBN\r\n" + "민경영\r\n" + "기자\r\n" + "사회\r\n"
			+ "business@mbn.co.kr\r\n" + "2016-12-25\r\n" + "MBN\r\n" + "서정표\r\n" + "기자\r\n" + "사회\r\n"
			+ "deep202@mbn.co.kr\r\n" + "2016-06-04\r\n" + "MBN\r\n" + "김한준\r\n" + "기자\r\n" + "사회\r\n"
			+ "beremoth@hanmail.net\r\n" + "2016-11-29\r\n" + "MBN\r\n" + "윤범기\r\n" + "기자\r\n" + "사회\r\n"
			+ "bkman96@mbn.co.kr\r\n" + "2017-04-01\r\n" + "MBN\r\n" + "이혁근\r\n" + "기자\r\n" + "사회\r\n"
			+ "root@mbn.co.kr\r\n" + "2017-03-30\r\n" + "MBN\r\n" + "조경진\r\n" + "기자\r\n" + "사회\r\n"
			+ "nice2088@mbn.co.kr\r\n" + "2016-12-27\r\n" + "MBN\r\n" + "한민용\r\n" + "기자\r\n" + "사회\r\n"
			+ "myhan@mbn.co.kr\r\n" + "2017-03-27\r\n" + "MBN\r\n" + "길기범\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "road@mbn.co.kr\r\n" + "2017-03-27\r\n" + "MBN\r\n" + "김용준\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "kimgija@mbn.co.kr\r\n" + "2016-06-07\r\n" + "MBN\r\n" + "최은미\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "cem@mbn.co.kr\r\n" + "2017-03-28\r\n" + "MBN\r\n" + "이동석\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "dslee@mbn.co.kr\r\n" + "2017-03-26\r\n" + "MBN\r\n" + "이권열\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "2kwon@mbn.co.kr\r\n" + "2017-03-07\r\n" + "MBN\r\n" + "이성식\r\n" + "기자\r\n" + "생활/문화\r\n"
			+ "mods@mbn.co.kr\r\n" + "2016-11-16\r\n" + "MBN\r\n" + "신지원\r\n" + "기자\r\n" + "생활경제\r\n"
			+ "jiwonah@mbn.co.kr\r\n" + "2016-06-19\r\n" + "MBN\r\n" + "엄해림\r\n" + "기자\r\n" + "세계\r\n"
			+ "umji@mbn.co.kr\r\n" + "2016-06-10\r\n" + "MBN\r\n" + "안병욱\r\n" + "기자\r\n" + "세계\r\n"
			+ "obo@mbn.co.kr\r\n" + "2017-03-13\r\n" + "MBN\r\n" + "정주영\r\n" + "기자\r\n" + "세계\r\n"
			+ "jaljalaram@mbn.co.kr\r\n" + "2017-03-23\r\n" + "MBN\r\n" + "이동화\r\n" + "기자\r\n" + "세계\r\n"
			+ "idoido@mbn.co.kr\r\n" + "2017-03-29\r\n" + "MBN\r\n" + "오태윤\r\n" + "기자\r\n" + "세계\r\n"
			+ "5tae@mbn.co.kr\r\n" + "2017-03-31\r\n" + "MBN\r\n" + "뉴스센터\r\n" + "정치\r\n"
			+ "mbnreporter01@mbn.co.kr\r\n" + "2017-03-31\r\n" + "MBN\r\n" + "전준영\r\n" + "기자\r\n" + "정치\r\n"
			+ "seasons@mk.co.kr\r\n" + "2017-03-26\r\n" + "MBN\r\n" + "원중희\r\n" + "기자\r\n" + "정치\r\n"
			+ "june12@mbn.co.kr\r\n" + "2017-03-28\r\n" + "MBN\r\n" + "김근희\r\n" + "기자\r\n" + "정치\r\n"
			+ "kgh@mbn.co.kr\r\n" + "2016-05-29\r\n" + "MBN\r\n" + "김문영\r\n" + "기자\r\n" + "정치\r\n"
			+ "nowmoon@mbn.co.kr\r\n" + "2017-03-28\r\n" + "MBN\r\n" + "박준우\r\n" + "기자\r\n" + "정치\r\n"
			+ "ideabank@mbn.co.kr\r\n" + "2017-03-29\r\n" + "MBN\r\n" + "황재헌\r\n" + "기자\r\n" + "정치\r\n"
			+ "just@mbn.co.kr\r\n" + "2016-08-06\r\n" + "MBN\r\n" + "황재헌\r\n" + "기자\r\n" + "정치\r\n"
			+ "hwang2335@gmail.com\r\n" + "2017-03-31\r\n" + "MBN\r\n" + "이해완\r\n" + "기자\r\n" + "정치\r\n"
			+ "parasa@mbn.co.kr\r\n" + "2016-10-20\r\n" + "MBN\r\n" + "송주영\r\n" + "기자\r\n" + "정치\r\n"
			+ "song@mbn.co.kr\r\n" + "2017-02-20\r\n" + "MBN\r\n" + "강영구\r\n" + "기자\r\n" + "정치\r\n"
			+ "ilove@mbn.co.kr\r\n" + "2016-12-25\r\n" + "MBN\r\n" + "이재호\r\n" + "기자\r\n" + "정치\r\n"
			+ "jay8166@mbn.co.kr\r\n" + "2017-01-01\r\n" + "MBN\r\n" + "김순철\r\n" + "기자\r\n" + "정치\r\n"
			+ "liberty@mbn.co.kr\r\n" + "2016-12-22\r\n" + "MBN\r\n" + "이상범\r\n" + "기자\r\n" + "정치\r\n"
			+ "boomsang@daum.net\r\n" + "2017-03-22\r\n" + "MBN\r\n" + "정규해\r\n" + "기자\r\n" + "정치\r\n"
			+ "spol@mbn.co.kr\r\n" + "2017-03-28\r\n" + "MBN\r\n" + "최인제\r\n" + "기자\r\n" + "증권\r\n"
			+ "copus@mbn.co.kr\r\n" + "2016-07-07\r\n" + "MBN\r\n" + "배정훈\r\n" + "기자\r\n" + "증권\r\n"
			+ "baejr@mbn.co.kr\r\n" + "2017-03-02\r\n" + "MBN\r\n" + "김경기\r\n" + "기자\r\n" + "증권\r\n"
			+ "goldgame@mbn.co.kr\r\n" + "2017-03-23\r\n" + "MBN\r\n" + "윤지원\r\n" + "기자\r\n" + "증권\r\n"
			+ "jwyuhn@gmail.com\r\n" + "2017-03-21\r\n" + "OSEN\r\n" + "강필주\r\n" + "기자\r\n" + "IT\r\n"
			+ "letmeout@osen.co.kr\r\n" + "2017-03-31\r\n" + "OSEN\r\n" + "신연재\r\n" + "기자\r\n" + "IT\r\n"
			+ "yj01@osen.co.kr\r\n" + "2016-12-26\r\n" + "OSEN\r\n" + "손찬익\r\n" + "기자\r\n" + "IT\r\n"
			+ "what@osen.co.kr\r\n" + "2017-03-07\r\n" + "OSEN\r\n" + "고용준\r\n" + "기자\r\n" + "게임/리뷰\r\n"
			+ "scrapper@osen.co.kr\r\n" + "2017-03-16\r\n" + "OSEN\r\n" + "민경훈\r\n" + "기자\r\n" + "공연/전시\r\n"
			+ "rumi@osen.co.kr\r\n" + "2017-03-31\r\n" + "OSEN\r\n" + "이동해\r\n" + "기자\r\n" + "자동차/시승기\r\n"
			+ "eastsea@osen.co.kr\r\n" + "2017-03-31\r\n" + "OSEN\r\n" + "백승철\r\n" + "기자\r\n" + "자동차/시승기\r\n"
			+ "baik@osen.co.kr\r\n" + "2016-11-29\r\n" + "OSEN\r\n" + "우충원\r\n" + "기자\r\n" + "자동차/시승기\r\n"
			+ "10bird@osen.kr\r\n" + "2016-11-08\r\n" + "OSEN\r\n" + "우충원\r\n" + "기자\r\n" + "자동차/시승기\r\n"
			+ "10bird@osen.co\r\n" + "2016-11-08\r\n" + "OSEN\r\n" + "강희수\r\n" + "기자\r\n" + "책\r\n"
			+ "100c@osen.co.kr\r\n" + "2017-04-01\r\n" + "OSEN\r\n" + "이균재\r\n" + "기자\r\n" + "통신/뉴미디어\r\n"
			+ "dolyng@osen.co.kr\r\n" + "2017-03-14\r\n" + "OSEN\r\n" + "최규한\r\n" + "기자\r\n" + "패션/뷰티\r\n"
			+ "dreamer@osen.co.kr\r\n" + "2017-01-17\r\n" + "OSEN\r\n" + "우충원\r\n" + "기자\r\n" + "패션/뷰티\r\n"
			+ "10bird@osen.co.kr\r\n" + "2017-03-31\r\n" + "SBS\r\n" + "김용태\r\n" + "기자\r\n" + "경제\r\n"
			+ "tai@sbs.co.kr\r\n" + "2017-04-01\r\n" + "SBS\r\n" + "김범주\r\n" + "기자\r\n" + "경제\r\n"
			+ "news4u@sbs.co.kr\r\n" + "2017-03-29\r\n" + "SBS\r\n" + "한세현\r\n" + "기자\r\n" + "경제\r\n"
			+ "vetman@sbs.co.kr\r\n" + "2017-03-31\r\n" + "SBS\r\n" + "손승욱\r\n" + "기자\r\n" + "경제\r\n"
			+ "ssw@sbs.co.kr\r\n" + "2017-03-28\r\n" + "SBS\r\n" + "최우철\r\n" + "기자\r\n" + "경제\r\n"
			+ "justrue1@sbs.co.kr\r\n" + "2017-01-09\r\n" + "SBS\r\n" + "전혜원\r\n" + "기자\r\n" + "경제\r\n"
			+ "sydney.chun@sbs.co.kr\r\n" + "2017-03-31)";

}
